;; -*- mode: eask; lexical-binding: t -*-

(package "pending"
         "0.1.0"
         "Async pending content placeholders")

(author "John Wiegley" "jwiegley@gmail.com")
(license "BSD-3-Clause")
(website-url "https://github.com/jwiegley/pending")
(keywords "convenience" "tools")

(package-file "pending.el")

(files "pending.el"
       "doc/pending.info"
       "doc/pending.texi"
       "README.md"
       "LICENSE.md")

(script "test" "eask test ert pending-test.el")

(source "gnu")

(depends-on "emacs" "27.1")
